=head1 NAME

Plack::Middleware::ErrorWithGitBlame - error with git-blame

=head1 SYNOPSIS

in your psgi file,

  use Plack::Builder;
  
  ### your app
  my $app = sub { 
      my $x = 2 / 0 # error!
      [200, [], ['x is '.$x]]; 
  };
  
  builder {
      enable 'ErrorWithGitBlame', parse_blame => 1;
      $app;
  };

=head1 AUTHOR

ytnobody E<lt>ytnobody@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
